baseURL = 'https://ashvetica.com'
noBuildLock = true
locale = 'en-au'
title = 'ashvetica'
theme = "ASHVETICA-THEME"

[params]
  mainSections = ["projects"]
  # color style
  color = 'linen'                           # linen, wheat, gray, light
  email = 'contact@ashvetica.com'           # email for footer
  author = 'Ashley B'                       # author name for footer
  pageAuthor = "Luk Ole"                    # Web Developer
  pageAuthorLink = "https://lukole.au"      # Link to developer site

  # header social icons
  instagram = 'ashvetica'           # instagram.com/YOUR_INSTAGRAM_ID
  behance = 'ashvetica'                         # behance.net/YOUR_BEHANCE_ID
  # rss = true                                # show rss icon

  # home page profile
  avatar = 'GRAVATAR_EMAIL'                 # gravatar email or image url
  name = 'Ashley B'
  bio = 'BIOGRAPHY'

# favicon = "favicon.ico"                   # customize the default favicon
# appleTouchIcon = "apple-touch-icon.png"   # customize the default Apple touch icon
